# This is a basic workflow to help you get started with Actions

name: CI

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      ####################################
      # Single app example. no tag prefix
      ####################################
      - name: Write version information
        run: |
          if [[ "${GITHUB_REF##*/}" == release/* || "${GITHUB_REF##*/}" == hotfix/* ]]; then
            INCREMENT=patch 
          else
            INCREMENT=minor
          fi

          mkdir -p .local
          python version.py $INCREMENT --format env > .local/build-env
          cat .local/build-env

      - name: Tag on main
        if: github.ref == 'refs/heads/main'
        run: |
          export GIT_AUTHOR_EMAIL=ci@fbi.com
          export GIT_COMMITTER_EMAIL=ci@fbi.com
          export GIT_AUTHOR_NAME="ci"
          export GIT_COMMITTER_NAME="ci"

          git tag -f \
            -a "${VERSION_TAG_PREFIX}${VERSION_TAG}" \
            -m "${VERSION_TAG_PREFIX}${VERSION_TAG}" 
          git push --force origin "${VERSION_TAG_PREFIX}${VERSION_TAG}"

      ####################################
      # Mulit service example. has tag prefix
      ####################################
      - name: Write version information
        run: |
          if [[ "${GITHUB_REF##*/}" == release/* || "${GITHUB_REF##*/}" == hotfix/* ]]; then
            INCREMENT=patch 
          else
            INCREMENT=minor
          fi

          mkdir -p .local
          python version.py $INCREMENT --tag-prefix=myservice-v --format env > .local/build-env
          cat .local/build-env

      - name: Tag on main
        if: github.ref == 'refs/heads/main'
        run: |
          export GIT_AUTHOR_EMAIL=ci@fbi.com
          export GIT_COMMITTER_EMAIL=ci@fbi.com
          export GIT_AUTHOR_NAME="ci"
          export GIT_COMMITTER_NAME="ci"

          git tag -f \
            -a "${VERSION_TAG_PREFIX}${VERSION_TAG}" \
            -m "${VERSION_TAG_PREFIX}${VERSION_TAG}" 
          git push --force origin "${VERSION_TAG_PREFIX}${VERSION_TAG}"
